# Generated by Django 6.0.6 on 2026-08-19 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_enrollment_payment_payment_type_and_more'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='shop.order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('BOOKING', 'Booking Deposit'), ('COURSE', 'Course Tuition'), ('ORDER', 'Shop Order')], default='BOOKING', max_length=30),
        ),
    ]
