# Generated by Django 5.2.17 on 2026-08-20 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0002_blockeddate_businesshours_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'New Enquiry'), ('IN_PROGRESS', 'In Progress'), ('RESPONDED', 'Responded'), ('CLOSED', 'Closed')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer Enquiry',
                'verbose_name_plural': 'Customer Enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('BRIDAL', 'Bridal & Wedding'), ('HAIRSTYLES', 'Hair Styling & Updos'), ('WIG_MELT', 'Wig Installation & Lace Melt'), ('TRANSFORMATION', 'Hair Transformation'), ('NATURAL_HAIR', 'Natural Hair & Maintenance'), ('EVENTS', 'Events & Special Occasions')], default='HAIRSTYLES', max_length=50)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, help_text='Short description or client testimonial excerpt.', max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this image is visible on the public gallery page.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_images', to='booking.servicecategory')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
