# Generated by Django 5.2.17 on 2026-08-18 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Service Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('short_description', models.CharField(help_text='Brief summary for cards and lists.', max_length=255)),
                ('description', models.TextField(help_text='Detailed service description.')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price in NGN. Leave empty if price is available on enquiry.', max_digits=10, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Estimated duration in minutes.', null=True)),
                ('featured', models.BooleanField(default=False, help_text='Highlight on homepage and top of services list.')),
                ('active', models.BooleanField(default=True, help_text='Whether this service is available for viewing/booking.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='booking.servicecategory')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
