# Generated by Django 6.0.6 on 2026-08-30 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Short description of this beauty category.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=275, unique=True)),
                ('featured_image', models.ImageField(blank=True, help_text='High-resolution editorial cover image.', null=True, upload_to='blog/covers/')),
                ('excerpt', models.TextField(help_text='Short teaser summary for listing cards, hero banners, and search previews.', max_length=500)),
                ('content', models.TextField(help_text='Full article body content with rich formatting.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], db_index=True, default='DRAFT', max_length=15)),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Highlight as a featured editorial story on the blog homepage.')),
                ('reading_time_minutes', models.PositiveIntegerField(default=3, help_text='Estimated read time in minutes (auto-calculated if left blank).')),
                ('views_count', models.PositiveIntegerField(default=0, help_text='Total page views.')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='Publication timestamp. Posts with future dates will remain scheduled.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, help_text='Custom SEO title tag (optional - defaults to article title).', max_length=160)),
                ('meta_description', models.CharField(blank=True, help_text='Custom search engine meta description (optional - defaults to excerpt).', max_length=255)),
                ('canonical_url', models.URLField(blank=True, help_text='Optional canonical override URL.')),
                ('author', models.ForeignKey(blank=True, help_text='Author of the article (defaults to staff user).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(help_text='Primary category for this article.', on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.blogcategory')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
