# Generated by Django 5.2.17 on 2026-08-18 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the training area.')),
                ('icon', models.CharField(blank=True, help_text='Optional icon identifier or emoji.', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display ordering weight.')),
                ('active', models.BooleanField(default=True, help_text='Designates whether this category is active.')),
            ],
            options={
                'verbose_name': 'Course Category',
                'verbose_name_plural': 'Course Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('short_description', models.CharField(help_text='Concise summary for course cards.', max_length=255)),
                ('full_description', models.TextField(help_text='Detailed course breakdown and syllabus overview.')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='academy/courses/')),
                ('duration', models.CharField(blank=True, help_text='e.g. 4 Weeks, 2 Days, or Self-Paced', max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Course fee in NGN. Leave blank if price is on enquiry.', max_digits=10, null=True)),
                ('format_type', models.CharField(choices=[('PHYSICAL', 'Physical Training'), ('ONLINE', 'Online Class'), ('HYBRID', 'Hybrid Program')], default='PHYSICAL', max_length=20)),
                ('active', models.BooleanField(default=True, help_text='Whether this course is publicly visible.')),
                ('featured', models.BooleanField(default=False, help_text='Whether to feature this course prominently.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='academy.coursecategory')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['-featured', '-created_at'],
            },
        ),
    ]
