# Generated by Django 5.2.17 on 2026-08-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='learning_outcomes',
            field=models.TextField(blank=True, help_text='Enter key skills/outcomes learned in this course, one per line.'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.TextField(blank=True, help_text='Optional prerequisites or recommended tools.'),
        ),
        migrations.AddField(
            model_name='course',
            name='target_audience',
            field=models.TextField(blank=True, help_text='Enter target student profiles for this course, one per line.'),
        ),
    ]
