# Generated by Django 5.2.17 on 2026-08-20 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_certificate_module_lesson_lessonprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this certificate is valid and active.'),
        ),
    ]
