# Generated by Django 5.2.17 on 2026-08-18 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0002_blockeddate_businesshours_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('BOOKING_CONFIRMATION', 'Booking Confirmation')], default='BOOKING_CONFIRMATION', max_length=50)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed')], default='SENT', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='booking.booking')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
