# Generated by Django 5.2.17 on 2026-08-20 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_certificate_is_active'),
        ('booking', '0002_blockeddate_businesshours_booking'),
        ('notifications', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationlog',
            options={'ordering': ['-sent_at'], 'verbose_name': 'Notification Log', 'verbose_name_plural': 'Notification Logs'},
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='academy.certificate'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='channel',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp')], default='EMAIL', max_length=20),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='academy.enrollment'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='shop.order'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='recipient',
            field=models.CharField(blank=True, default='', help_text='Email address or phone number of recipient.', max_length=255),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='subject_or_summary',
            field=models.CharField(blank=True, help_text='Subject line or summary snippet.', max_length=255),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='booking.booking'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('BOOKING_CONFIRMATION', 'Booking Confirmation'), ('APPOINTMENT_REMINDER', 'Appointment Reminder'), ('APPOINTMENT_CANCELLATION', 'Appointment Cancellation'), ('APPOINTMENT_RESCHEDULED', 'Appointment Rescheduled'), ('ACADEMY_ENROLMENT', 'Academy Enrolment'), ('COURSE_COMPLETION', 'Course Completion'), ('ORDER_CONFIRMATION', 'Order Confirmation')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
