# Generated by Django 6.0.6 on 2026-08-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notificationlog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('BOOKING_CONFIRMATION', 'Booking Confirmation'), ('APPOINTMENT_REMINDER', 'Appointment Reminder'), ('APPOINTMENT_CANCELLATION', 'Appointment Cancellation'), ('APPOINTMENT_RESCHEDULED', 'Appointment Rescheduled'), ('ACADEMY_ENROLMENT', 'Academy Enrolment'), ('COURSE_COMPLETION', 'Course Completion'), ('ORDER_CONFIRMATION', 'Order Confirmation'), ('POST_APPOINTMENT_REVIEW', 'Post-Appointment Review Request')], max_length=50),
        ),
    ]
